# This docker-compose.yml file is used to build and test quickly
# a specific version of Dolibarr
#
# Before build, define the variable DOLI_VERSION as following:
# $ export DOLI_VERSION=4.0.4
# And then, you can run :
# $ docker-compose up
#
# More information about Docker-compose : https://docs.docker.com/compose/

#version: "3.8"

networks:
    in-pod:
        internal: true
    ex-pod:
        internal: false

secrets:
    mysql-user:
        file: ./examples/with-secrets/secrets/mysql_user.secret
    mysql-password:
        file: ./examples/with-secrets/secrets/mysql_password.secret

services:
    mariadb:
        image: mariadb:10.6.17
        secrets:
            - mysql-user
            - mysql-password
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
            MYSQL_DATABASE: "dolibarr2"
            MYSQL_USER_FILE: "/run/secrets/mysql-user"
            MYSQL_PASSWORD_FILE: "/run/secrets/mysql-password"
        ports:
            - "3320:3306"
        networks:
            - in-pod
            - ex-pod

    cron:
        build:
            context: ./images/19.0.2-php8.2
        image: tuxgasy/dolibarr:19.0.2-php8.2
        secrets:
            - mysql-user
            - mysql-password
        environment:
            DOLI_CRON: 1
            DOLI_CRON_USER: administrator
            DOLI_DB_USER_FILE: /run/secrets/mysql-user
            DOLI_DB_PASSWORD_FILE: /run/secrets/mysql-password
            DOLI_ADMIN_LOGIN: administrator
            DOLI_ADMIN_PASSWORD: admin456
            DOLI_DB_HOST: mariadb
            DOLI_DB_NAME: dolibarr2
            DOLI_URL_ROOT: http://0.0.0.0
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        networks:
            - in-pod

    web:
        build:
            context: ./images/19.0.2-php8.2
        image: tuxgasy/dolibarr:19.0.2-php8.2
        secrets:
            - mysql-user
            - mysql-password
        volumes:
            - type: bind
              source: ./dolibarr/htdocs/custom
              target: /var/www/html/custom
            - type: bind
              source: ./documents/doli20
              target: /var/www/documents
            - type: bind
              source: ./dolibarr/htdocs
              target: /var/www/htdocs
        depends_on:
            - mariadb
        environment:
            DOLI_INSTANCE_UNIQUE_ID: xxxx
            DOLI_DB_USER_FILE: "/run/secrets/mysql-user"
            DOLI_DB_PASSWORD_FILE: "/run/secrets/mysql-password"
            DOLI_ADMIN_LOGIN: "administrator"
            DOLI_ADMIN_PASSWORD: "admin456"
            DOLI_DB_HOST: mariadb
            DOLI_DB_NAME: dolibarr2
            DOLI_URL_ROOT: 'http://0.0.0.0'
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        ports:
            - "8080:80"
        networks:
            - in-pod
            - ex-pod
